AWSTemplateFormatVersion: '2010-09-09'
Description: Trevy Web Service (ALB + ECS Fargate) with HTTPS, autoscaling, and dynamic secrets injection

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
  PrivateSubnets:
    Type: List<AWS::EC2::Subnet::Id>
  ClusterName:
    Type: String
    Default: trevy-cluster
  AppImage:
    Type: String
    Description: ECR image URI for trevy-platform web service
  DesiredCount:
    Type: Number
    Default: 2
  MinCapacity:
    Type: Number
    Default: 2
  MaxCapacity:
    Type: Number
    Default: 10
  Cpu:
    Type: Number
    Default: 2048
  Memory:
    Type: Number
    Default: 4096
  TaskExecutionRoleArn:
    Type: String
  AppTaskRoleArn:
    Type: String
  AppLogGroupName:
    Type: String
    Default: /ecs/trevy-platform
  AcmCertificateArn:
    Type: String
    Description: ACM certificate ARN for the HTTPS listener (api domain)
  AppUrl:
    Type: String
    Description: Public API base URL (e.g., https://api.example.com)
  FrontendUrl:
    Type: String
    Description: Frontend origin URL for CORS (e.g., https://app.example.com)
  FubBaseUrl:
    Type: String
    Default: https://api.followupboss.com/v1
  MailgunEndpoint:
    Type: String
    Default: api.mailgun.net
  StripeAccountId:
    Type: String
    Default: ''
  RdsSecurityGroupId:
    Type: String
    Description: Security group ID of the RDS Postgres instance
  RedisSecurityGroupId:
    Type: String
    Description: Security group ID of the ElastiCache Redis cluster
  DBSecretArn:
    Type: String
    Description: "Secrets Manager ARN for DB JSON secret (keys: host, port, username, password, database)"
  RedisSecretArn:
    Type: String
    Description: "Secrets Manager ARN for Redis JSON secret (keys: host, port, password)"
  AppSecretsArn:
    Type: String
    Description: "Secrets Manager ARN for application JSON secret with all app secrets"
  # SQS Worker Configuration
  SqsCdpWorkers:
    Type: Number
    Default: 10
    Description: Number of SQS workers for CDP ingest (scale up to 20-30 for large imports)
  SqsSleep:
    Type: Number
    Default: 3
    Description: Seconds to sleep when queue is empty
  SqsTries:
    Type: Number
    Default: 3
    Description: Number of times to attempt a job
  SqsTimeout:
    Type: Number
    Default: 120
    Description: Maximum seconds a job can run
  SqsBackoff:
    Type: Number
    Default: 10
    Description: Seconds to wait before retrying failed job
  SqsMaxJobs:
    Type: Number
    Default: 1000
    Description: Maximum jobs before worker restarts (0 = unlimited)
  SqsMaxTime:
    Type: Number
    Default: 3600
    Description: Maximum seconds before worker restarts (0 = unlimited)

Resources:
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ECS web service tasks
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref AlbSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          DestinationSecurityGroupId: !Ref RdsSecurityGroupId
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          DestinationSecurityGroupId: !Ref RedisSecurityGroupId
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: trevy-web-alb-v2
      Scheme: internet-facing
      Type: application
      Subnets: !Ref PublicSubnets
      SecurityGroups:
        - !Ref AlbSecurityGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: trevy-web-tg-v2
      TargetType: ip
      VpcId: !Ref VpcId
      Protocol: HTTP
      Port: 8080
      HealthCheckEnabled: true
      HealthCheckProtocol: HTTP
      HealthCheckPath: /api/v1/health
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: '200'
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '30'
        - Key: stickiness.enabled
          Value: 'false'

  HttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref AcmCertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: '443'
            StatusCode: HTTP_301

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: trevy-web
      Cpu: !Ref Cpu
      Memory: !Ref Memory
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !Ref TaskExecutionRoleArn
      TaskRoleArn: !Ref AppTaskRoleArn
      ContainerDefinitions:
        - Name: web
          Image: !Ref AppImage
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
          Essential: true
          LinuxParameters:
            InitProcessEnabled: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref AppLogGroupName
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: web
          Environment:
            - Name: APP_ENV
              Value: production
            - Name: APP_DEBUG
              Value: 'false'
            - Name: APP_URL
              Value: !Ref AppUrl
            - Name: DB_CONNECTION
              Value: pgsql
            - Name: CACHE_DRIVER
              Value: redis
            - Name: SESSION_DRIVER
              Value: redis
            - Name: QUEUE_CONNECTION
              Value: redis
            - Name: LOG_CHANNEL
              Value: stderr
            - Name: FRONTEND_URL
              Value: !Ref FrontendUrl
            - Name: MAILGUN_BASE_URL
              Value: !Ref MailgunEndpoint
            - Name: FUB_BASE_URL
              Value: !Ref FubBaseUrl
            - Name: STRIPE_ACCOUNT_ID
              Value: !Ref StripeAccountId
            - Name: SECRETS_ARN
              Value: !Ref AppSecretsArn
            # SQS Worker Configuration
            - Name: SQS_CDP_WORKERS
              Value: !Ref SqsCdpWorkers
            - Name: SQS_SLEEP
              Value: !Ref SqsSleep
            - Name: SQS_TRIES
              Value: !Ref SqsTries
            - Name: SQS_TIMEOUT
              Value: !Ref SqsTimeout
            - Name: SQS_BACKOFF
              Value: !Ref SqsBackoff
            - Name: SQS_MAX_JOBS
              Value: !Ref SqsMaxJobs
            - Name: SQS_MAX_TIME
              Value: !Ref SqsMaxTime
            # Microsoft/Outlook Configuration
            - Name: OUTLOOK_SEND_ENABLED
              Value: 'true'
            - Name: OUTLOOK_SEND_THRESHOLD
              Value: '100'
            - Name: OUTLOOK_REPLY_CHECK_ENABLED
              Value: 'true'
            - Name: OUTLOOK_REPLY_CHECK_INTERVAL
              Value: '5'
            - Name: OUTLOOK_REPLY_CHECK_WINDOW
              Value: '10'
          Secrets:
            # DB secrets
            - Name: DB_HOST
              ValueFrom: !Sub "${DBSecretArn}:host::"
            - Name: DB_PORT
              ValueFrom: !Sub "${DBSecretArn}:port::"
            - Name: DB_DATABASE
              ValueFrom: !Sub "${DBSecretArn}:dbname::"
            - Name: DB_USERNAME
              ValueFrom: !Sub "${DBSecretArn}:username::"
            - Name: DB_PASSWORD
              ValueFrom: !Sub "${DBSecretArn}:password::"
            # Redis secrets
            - Name: REDIS_HOST
              ValueFrom: !Sub "${RedisSecretArn}:host::"
            - Name: REDIS_PORT
              ValueFrom: !Sub "${RedisSecretArn}:port::"
            - Name: REDIS_PASSWORD
              ValueFrom: !Sub "${RedisSecretArn}:password::"
            # App secrets from trevy/app/secrets
            - Name: AI_SERVICE_BASE_URL
              ValueFrom: !Sub "${AppSecretsArn}:AI_SERVICE_BASE_URL::"
            - Name: SERVICE_KEY_ID
              ValueFrom: !Sub "${AppSecretsArn}:SERVICE_KEY_ID::"
            - Name: SERVICE_SECRET
              ValueFrom: !Sub "${AppSecretsArn}:SERVICE_SECRET::"
            - Name: AI_SERVICE_TIMEOUT
              ValueFrom: !Sub "${AppSecretsArn}:AI_SERVICE_TIMEOUT::"
            # Sentry secrets
            - Name: SENTRY_LARAVEL_DSN
              ValueFrom: !Sub "${AppSecretsArn}:SENTRY_LARAVEL_DSN::"
            - Name: SENTRY_TRACES_SAMPLE_RATE
              ValueFrom: !Sub "${AppSecretsArn}:SENTRY_TRACES_SAMPLE_RATE::"
            - Name: SENTRY_ENVIRONMENT
              ValueFrom: !Sub "${AppSecretsArn}:SENTRY_ENVIRONMENT::"
            # Microsoft OAuth secrets
            - Name: MICROSOFT_CLIENT_ID
              ValueFrom: !Sub "${AppSecretsArn}:MICROSOFT_CLIENT_ID::"
            - Name: MICROSOFT_CLIENT_SECRET
              ValueFrom: !Sub "${AppSecretsArn}:MICROSOFT_CLIENT_SECRET::"
            - Name: MICROSOFT_REDIRECT_URI
              ValueFrom: !Sub "${AppSecretsArn}:MICROSOFT_REDIRECT_URI::"
            - Name: MICROSOFT_TENANT_ID
              ValueFrom: !Sub "${AppSecretsArn}:MICROSOFT_TENANT_ID::"

  Service:
    Type: AWS::ECS::Service
    DependsOn:
      - HttpsListener
    Properties:
      Cluster: !Ref ClusterName
      TaskDefinition: !Ref TaskDefinition
      ServiceName: trevy-web
      LaunchType: FARGATE
      DesiredCount: !Ref DesiredCount
      EnableExecuteCommand: true
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: !Ref PrivateSubnets
          SecurityGroups:
            - !Ref ServiceSecurityGroup
      LoadBalancers:
        - TargetGroupArn: !Ref TargetGroup
          ContainerName: web
          ContainerPort: 8080
      DeploymentConfiguration:
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      HealthCheckGracePeriodSeconds: 60

  ScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: !Ref MaxCapacity
      MinCapacity: !Ref MinCapacity
      ResourceId: !Sub service/${ClusterName}/${Service.Name}
      RoleARN: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  CpuScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: trevy-web-cpu-scaling
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        TargetValue: 60
        ScaleInCooldown: 60
        ScaleOutCooldown: 60

Outputs:
  AlbDnsName:
    Value: !GetAtt LoadBalancer.DNSName
  ServiceName:
    Value: !GetAtt Service.Name
  TargetGroupArn:
    Value: !Ref TargetGroup